spring:
  datasource:
    platform: mysql
    url: jdbc:mariadb://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:mydb}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:password}
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: ${SQL_QUERIES_SHOW:false}
    properties:
      hibernate:
        format_sql: ${SQL_QUERIES_FORMAT:false}

